MAE-84: Fixing an error that prevented users from creating DD batches
Whan trying to create an Instruction batch or a Payment collection
batch, the following fatal error will appear after the user select the
batch name and originator number and clicking Next :

Error: Call to undefined method CRM_ManualDirectDebit_Form_BatchTransaction::addSearchFieldMetadata() in CRM_Contribute_BAO_Query::buildSearchForm

which prevent the user from creating the batch and exporting it.

The error caused by the following line inside
CRM_ManualDirectDebit_Form_BatchTransaction class :

CRM_Contribute_BAO_Query::buildSearchForm($this);

The line above pass an instant of the current form object to
the buildSearchForm, but the CRM_ManualDirectDebit_Form_BatchTransaction
class is of type CRM_Contribute_Form where the buildSearchForm method
expect a class of type CRM_Contribute_Form_Search and call some method
that are only defined inside it such as addSearchFieldMetadata().

The batch creation, submition and exporting in general inside DD extension is copied
from CiviCRM core with some modificaions (at the navigation menu see
Contribution >> Accounting Batches), that's why CRM_ManualDirectDebit_Form_BatchTransaction
extends CRM_Contribute_Form since this how the core class CRM_Financial_Form_BatchTransaction
was defined before, but since CiviCRM > 5.X many changes happen around
that area that resulted in changing the class that
CRM_Financial_Form_BatchTransaction extends to be
CRM_Contribute_Form_Search instead of CRM_Contribute_Form, and since we
are now targeting CiviCRM 5.19 for membershipextras product V2, this
issue appeared also on DD extension which still extends
CRM_Contribute_Form.

In this commit I changed the class to follow the class that it was
copied from which is to extend CRM_Contribute_Form_Search instaed of
CRM_Contribute_Form, which fixes the issue.

Also I did some checking on the class to ensure that no other function
is broken by this change and it seems to be safe.